Register page
Natrosvili/Capstone-Project-movies-series-app pull request #22
Opened 2022-12-12 13:53 UTC by Natrosvili

here is my Register Page. Hope you'll like it :-).

2022-12-12 14:21 UTC, stefankorder requested changes
LGTM! Please take a look at my comments.

2022-12-12 14:21 UTC, stefankorder commented on pages/login.js
> +              onChange={() => setVisible(!visible)}
Add the following:

```suggestion
              onChange={() => setVisible(!visible)}
              checked={visible}
```

2022-12-12 14:21 UTC, stefankorder commented on pages/register.js
> +            />
Try to write a checkbox component, instead of writing the same code multiple times.

2022-12-12 14:21 UTC, stefankorder commented on pages/register.js
> +            />
Try to write a checkbox component, instead of writing the same code multiple times.

2022-12-12 14:21 UTC, stefankorder commented on pages/register.js
> +  const [visible2, setVisible2] = useState(false);
Try to write a checkbox component, instead of writing the same code multiple times. You can handle the state inside the component.

2022-12-13 10:39 UTC, actyralf requested changes
Hey Georgios,

just a few comments on component structure...

2022-12-13 10:39 UTC, actyralf commented on pages/login.js
> -              onChange={handleVisibility}
use your new `<Checkbox/>` component here instead of the generic `<input/>`

2022-12-13 10:39 UTC, actyralf commented on components/Checkbox.js
> +}
You don't need the fragments (`<></>`), please remove them.
You don't need `type` either, because this is a checkbox component, `type` could always be checkbox.
You will need the `checked` property though to set the value of the checkbox from outside.

2022-12-13 10:39 UTC, actyralf commented on pages/login.js
Please have a look at your styled components - I'm sure many of them can be reused on the register page (and on other pages later).

Please consider:

1. Moving styled components to separate files and importing them where needed.
2. Making styled components more flexible by using props (e.g. instead of `StyledDiv1`, `StyledDiv2` etc. use sth. like `<StyledDiv variant="your-variant"></StyledDiv>`

2022-12-13 23:26 UTC, actyralf requested changes
I'm sorry, but it seems you misunderstood my point :-(

Please see my comment below... I'll explain this tomorrow to the whole course because many of you seem to struggle with that.

2022-12-13 23:26 UTC, actyralf commented on components/MoviesSeriesSections.js
> +`;
Oh sorry - that seems to have been a misunderstanding :-(
What I meant was to identify only props that should be different for different use cases.
If you have a button component for example, you might want to have 3 different variants of it (let's say: highlight, standard and borderless). So you should do all of your styling within your styled component as usual but set the background color and maybe the shadow differently depending on the value of a prop you call "variant".
Then you could later use it like this: 
```
<Button variant="highlight">Click me</Button>
```
or
```
<Button variant="standard">Click me</Button>
```

The idea was to look at similarities and differences of certain components and then design these with the appropriate props.

I guess it was a lot of work to pass all of the css properties as props, but it's really not useful that way...
Now you have to set every detail as a prop and your code has become bigger instead of smaller :-(

2022-12-14 15:17 UTC, stefankorder commented on pages/movies.js
>      <>
You don't need a fragment `<> / </>` at this point. Your `section` already nest the other tags.

2022-12-15 14:12 UTC, merged